
version: 2

models:
  - name: stg_payments
    description: "An example payments dbt model"
    columns:
      - name: order_id
        description: "order id (not necessarily unique)"  
        tests:
          - not_null		
      - name: payment_method
          - not_null
      - name: amount
        description: "amount spent on order in USD"  
        tests:
          - not_null